### ISSUE TITLE
npm install results in errors

### ISSUE THREAD

**Issue by WaldemarEnns** [stalniy/casl-vue-api-example#5]
# Problem
I try to install the dependencies and always result in the following error:

**Console output**
```
[...]
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-2d233489/fp/zipAll.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-8cbf4559/fp/zipWith.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-a8686903/fp/zipObjectDeep.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-2d233489/fp/zipObj.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-2d233489/fp/zipObject.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-a8686903/fp/zipWith.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-2d233489/fp/zipObjectDeep.js'
npm WARN tar ENOENT: no such file or directory, open '/Volumes/Samsung_T5/private/casl-vue-api-example/node_modules/.staging/lodash-2d233489/fp/zipWith.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/enux/.npm/_logs/2020-01-31T09_36_37_228Z-debug.log
```

**Logfile output**
```
14347 silly saveTree ├─┬ vue-template-compiler@2.5.16
14347 silly saveTree │ ├── de-indent@1.0.2
14347 silly saveTree │ └── he@1.1.1
14347 silly saveTree ├── vue@2.5.16
14347 silly saveTree ├── vuetify@1.0.11
14347 silly saveTree └── vuex@3.0.1
14348 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...4.0","lodash.uniq":"^'
14348 verbose stack     at JSON.parse (<anonymous>)
14348 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
14348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
14348 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:85:5)
14349 verbose cwd /Volumes/Samsung_T5/private/casl-vue-api-example
14350 verbose Darwin 19.2.0
14351 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
14352 verbose node v12.6.0
14353 verbose npm  v6.13.1
14354 error Unexpected end of JSON input while parsing near '...4.0","lodash.uniq":"^'
14355 verbose exit [ 1, true ]
```

## How to reproduce
1. `git clone https://github.com/stalniy/casl-vue-api-example.git`
2. `cd casl-vue-api-example`
(@vue/cli already installed - also tryied with re-installing it but indeed, the error lays somewhere else ...)
3. `npm install`

## Solution proposal
I tried it with deleting my package-lock.json but it didn't help me.

**Comment by stalniy** [comment]
Try to use `npm ci` instead of `npm install`

**Comment by stalniy** [comment]
Also please send me your:

```sh
node -v
# and
npm -v
```

**Update**: this is mine:
```sh
[sergii@sergious casl-vue-api-example]$ node -v
v12.13.0
[sergii@sergious casl-vue-api-example]$ npm -v
6.13.6
```

works good

**Comment by WaldemarEnns** [comment]
> Try to use npm ci instead of npm install

This helped me out! Thank you :)

My node and npm versions are:
```shell
npm -v
6.13.1

node -v
v12.6.0

Thank you!
```
